import Head from "next/head";
import Menu from "@/components/menu";
import ShoppingCart from "@/components/shoppingCart";

export default function Layout({
  children,
  title,
}: {
  children: React.ReactNode;
  title: string;
}) {
  return (
    <div>
      <Head>
        <title>Github Merch {title ? ` | ${title}` : ""}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Menu />
      <div className="w-full mx-auto flex flex-col items-center">{children}</div>
      <ShoppingCart />
    </div>
  );
}
