import Head from "next/head";
import Navbar from "@/components/navbar";
import ShoppingCart from "@/components/shoppingCart";
import { Poppins } from "@next/font/google";

const font = Poppins({
  weight: ["400", "500", "700"],
  style: ["normal", "italic"],
  subsets: ["latin"],
});

export default function Layout({
  children,
  title,
}: {
  children: React.ReactNode;
  title: string;
}) {
  return (
    <>
      <Head>
        <title>Next Store {title ? ` | ${title}` : ""}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={`${font.className} bg-white`}>
        <Navbar />
        <div className="w-full mx-auto flex flex-col items-center">
          {children}
        </div>
        <ShoppingCart />
      </div>
    </>
  );
}
